### ISSUE TITLE
USER_SOURCES_DIR: Provide more than one directory

### ISSUE THREAD

**Issue by joewkr** [joewkr/open-SURFEX#4]
A directory with user source files could be provided via `USER_SOURCES_DIR` option, but sometimes sources from several directories should be used. It should be possible to define a list of user directories through `USER_SOURCES_DIR`.

**Comment by alapha23** [comment]
Thank you for providing this feature!

From what I understand, `convert_ecoclimap_param.f90` reads input from ECOCLIMAP dataset, which contains data in ascii form, and the ascii data would be written to binary

I am wondering, where are the output binary data files located? Should we always execute this command under `open-SURFEX/MY_RUN/ECOCLIMAP`?

Also, for each dataset under `MY_RUN/NAMELIST`, I found text files instead ascii files. 
So where are the ascii files we are converting?

**Comment by joewkr** [comment]
Yes, `CONVERT_ECOCLIMAP_PARAM` should be always executed under `open-SURFEX/MY_RUN/ECOCLIMAP` because it uses relative paths to find ASCII data. This program converts `ecoclimapI_covers_param.dat`, `ecoclimapII_af_covers_param.dat` and `ecoclimapII_eu_covers_param.dat` to binary form and its output is stored in the same directory.

Files under `MY_RUN/NAMELIST` are configuration files for Open-SURFEX.
