### ISSUE TITLE
Could you please suggest what version is this open-SURFEX?

### ISSUE THREAD

**Issue by alapha23** [joewkr/open-SURFEX#5]
Hi!

Could you please suggest what version is this open-SURFEX? I think the latest open version should be 8.1. 

Thank you in advance!

**Comment by joewkr** [comment]
Hi! This fork is in sync with the latest available open-SURFEX version from Météo-France. And currently this version is 8.1 (34f25b03) from Feb 8 2018.

**Comment by alapha23** [comment]
Thank you for the reply!
