### ISSUE TITLE
Set up AppVeyor builds

### ISSUE THREAD

**Issue by joewkr** [joewkr/open-SURFEX#7]
It would be nice to have Windows-based CI builds to test cmake-based build system.

**Comment by alapha23** [comment]
Hi!

I was curious so I forked and tried to build on AppVeyor.
It seems there are some features not supported and I believe there could be even more. 
I am just wondering, what could AppVeyor help this project?

```
The project file "grib_api_lib\grib_api_lib.vcproj" is in the ".vcproj" file format, which MSBuild no longer supports. Please convert the project by opening it in the Visual Studio IDE or running the conversion tool, or use MSBuild 3.5 or earlier to build it.
```

**Comment by joewkr** [comment]
Hi,

after quite some trials, I was able to build Open-SURFEX in AppVeyor, though only with a custom build of cmake. AppVeyor adds just one more check to be sure that problems raised in #6 won't appear in future.
