### ISSUE TITLE
output pf5 or other diagnostics

### ISSUE THREAD

**Issue by xushanthu-2014** [joewkr/open-SURFEX#9]
Hello hope this message finds you well!
I am a user who is using your open-SURFEX and wants to output pf5 (or the f2 factor from the surfex codes). I found that this variables is a local variable in the isba.f90 script (please correct me if I missed something). So how can I output it? by the way, I found that in https://github.com/joewkr/open-SURFEX/blob/master/src/SURFEX/modd_diag_misc_isban.F90, there is a comment:
!       B. Decharme 07/2012 : New diag for DIF under LSURF_MISC_DIF key
!!                               F2 stress
!!                               Root zone swi, wg and wgi
!!                               swi, wg and wgi comparable to ISBA-FR-DG2 and DG3 layers
but I didn't find f2 stress in the type DIAG_MISC_ISBA_t. And I found from https://www.umr-cnrm.fr/surfex/spip.php?article96 LSURF_MISC_DIF allows people to output diagnostics as the users wish (please correct me if I was wrong). So how can I use that?
By the way, I found that from the definition, f2 seems has a same calculation as liquid soil wetness index (swirl). Is that correct? can I use swi as f2?
Thanks and hope for your early reply!
Sincerely

**Comment by joewkr** [comment]
Hi,

this repository is not the the official open-SURFEX version by Météo-France, but rather a fork made for testing the new build system. So, I do not have a full overview of all the SURFEX components and could not provide a complete answer to your questions. I'd recommend contacting  surfex-support@meteo.fr to get more details.

Concerning the LSURF_MISC_DIF option, it could be enabled in your OPTIONS.nam file in the NAM_DIAG_ISBAn namelist. Assuming that you have no NAM_DIAG_ISBAn in your OPTIONS.nam, adding:

```
&NAM_DIAG_ISBAn
   LSURF_MISC_DIF=.TRUE.,
/
```

to your OPTIONS.nam should suffice. If you already have NAM_DIAG_ISBAn, just add `LSURF_MISC_DIF=.TRUE.,` to this namelist. But please keep in mind that this namelist option just enables some additional diagnostics for ISBA DIF and would make no effect with ISBA 2-L or 3-L. Also this option operates with a predefined set of diagnostics and does not allow adding new diagnostics via namelist options. So, if the diagnostic in question does not appear with this/other option(s) then, I'm afraid, the only way to get the required output would be modifying the source code.
